services:
  - type: web
    name: leaf-area-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn plant_disease_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /docs
    autoDeploy: true 