services:
  - type: web
    name: leaf-area-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CUDA_VISIBLE_DEVICES
        value: -1
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: PYTHONPATH
        value: .
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_WORKERS
        value: 2
      - key: TIMEOUT_KEEP_ALIVE
        value: 75
      - key: MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 2
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 