services:
  - type: web
    name: leaf-area-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn plant_disease_api:app --host 0.0.0.0 --port $PORT --workers 2 --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /docs
    autoDeploy: true
    plan: starter 