services:
  - type: web
    name: plant-disease-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn plant_disease_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: model-storage
      mountPath: /opt/render/project/src
      sizeGB: 1 