name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install fastapi uvicorn tensorflow numpy python-multipart
    - name: Run evaluation
      run: python3 evaluate_plant_disease_model.py
